### ISSUE TITLE
GUI on CPU

### ISSUE THREAD

**Issue by levi0809** [lyndonzheng/Pluralistic-Inpainting#9]
Wonderful work.
I've downloaded your pre-trained model.
I'd like to run the GUI on my CPU since the server seemly could not open your GUI program on Command Line: 
qt.qpa.screen: QXcbConnection: Could not connect to display
Could not connect to any X display.

I tried to run 'python3 ui_main.py --gpu_ids -1', but there are lots of bugs:
ConnectionRefusedError: [Errno 61] Connection refused
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8095): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x126ff4438>: Failed to establish a new connection: [Errno 61] Connection refused',))
ERROR:visdom:[Errno 61] Connection refused
AttributeError: 'ui_model' object has no attribute 'model'
[1]    87369 abort      python3 ui_main.py --gpu_ids -1

Please help me to solve it. Thank you!

**Comment by lyndonzheng** [comment]
@levi0809 Our model trained on GPU and didn't saved to CPU model. You need run the model with GPU.

**Comment by levi0809** [comment]
Traceback (most recent call last):
  File "/media/sdc/yjchai/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/media/sdc/yjchai/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/media/sdc/yjchai/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/sdc/yjchai/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/media/sdc/yjchai/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/media/sdc/yjchai/anaconda3/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/media/sdc/yjchai/anaconda3/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/media/sdc/yjchai/anaconda3/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/media/sdc/yjchai/anaconda3/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/media/sdc/yjchai/anaconda3/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/media/sdc/yjchai/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 196, in connect
    conn = self._new_conn()
  File "/media/sdc/yjchai/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7ffb50a38898>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/sdc/yjchai/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/media/sdc/yjchai/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/media/sdc/yjchai/anaconda3/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8095): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffb50a38898>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/sdc/yjchai/anaconda3/lib/python3.7/site-packages/visdom/__init__.py", line 548, in _send
    data=json.dumps(msg),
  File "/media/sdc/yjchai/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 559, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/media/sdc/yjchai/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/media/sdc/yjchai/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/media/sdc/yjchai/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8095): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffb50a38898>: Failed to establish a new connection: [Errno 111] Connection refused'))
ERROR:visdom:[Errno 111] Connection refused

**Comment by AlexanderLutsenko** [comment]
> Wonderful work.
> I've downloaded your pre-trained model.
> I'd like to run the GUI on my CPU since the server seemly could not open your GUI program on Command Line:
> qt.qpa.screen: QXcbConnection: Could not connect to display
> Could not connect to any X display.
> 
> I tried to run 'python3 ui_main.py --gpu_ids -1', but there are lots of bugs:
> ConnectionRefusedError: [Errno 61] Connection refused
> requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8095): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x126ff4438>: Failed to establish a new connection: [Errno 61] Connection refused',))
> ERROR:visdom:[Errno 61] Connection refused
> AttributeError: 'ui_model' object has no attribute 'model'
> [1] 87369 abort python3 ui_main.py --gpu_ids -1
> 
> Please help me to solve it. Thank you!

Don't worry about the X display.
The real setback is the pre-trained networks being wrapped in `DataParallel` module which won't work on CPU. Upon saving the wrapped model, `DataParallel` adds "module." prefix to the parameter names. When you run the script with `--gpu_ids -1` option, the model does not get wrapped and thus expects the checkpoint  file to contain parameters with the original names. More on that situation is [here](https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686/22).
A possible quick-and-dirty workaround is to remove the prefix from the names in the loaded state_dict before you initialize your network with it.

base_model.py/load_networks
```
...
try:
	state_dict = torch.load(path)
	state_dict = {name.replace('module.', '', 1) : param for name, param in state_dict.items()}
	net.load_state_dict(state_dict)
except:
...
```

With this little tweak, the GUI demo works like a charm on my CPU-only machine
